version: "3"

networks:
  local-symfony-environment:

services:
  web:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./apps:/var/www/apps
    networks:
      - local-symfony-environment
    depends_on:
      - app
    
  app:
    container_name: symfony-php
    build: 
      context: .
      dockerfile: ./symfony/Dockerfile
    ports:
      - "9000:8000"
    volumes:
      - ./apps:/var/www/apps
    working_dir: /var/www/apps
    networks:
      - local-symfony-environment
